import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import selectorParser from "postcss-selector-parser";

const marketingRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const sourceCssPath = path.join(
	marketingRoot,
	"src/styles/vendor/linear/navbar/source.css",
);
const naturalizedCssPath = path.join(
	marketingRoot,
	"src/styles/vendor/linear/navbar/naturalized.css",
);
const sourceDataPath = path.join(
	marketingRoot,
	"src/components/generated/navbar-source-data.ts",
);
const naturalizedDataPath = path.join(
	marketingRoot,
	"src/components/generated/navbar-data.ts",
);
const sourceScriptPath = path.join(
	marketingRoot,
	"src/scripts/navbar-extracted.ts",
);
const naturalizedScriptPath = path.join(marketingRoot, "src/scripts/navbar.ts");
const renameMapPath = path.join(marketingRoot, "tools/rename-map/navbar.json");
const scopeClass = "opaline-navbar-scope";

const replaceTokens = (source, replacements) => {
	let result = source;
	for (const [from, to] of Object.entries(replacements).toSorted(
		([left], [right]) => right.length - left.length,
	)) {
		result = result.replaceAll(from, to);
	}
	return result;
};

const transformSelector = selectorParser((selectors) => {
	selectors.each((selector) => {
		selector.walkClasses((node) => {
			const renamed = renameMap.classes[node.value];
			if (renamed) node.value = renamed;
		});
		selector.walkAttributes((node) => {
			const renamed = renameMap.attributes[node.attribute];
			if (renamed) node.attribute = renamed;
			if (node.attribute === "data-theme" && node.value === "light") {
				node.replaceWith(selectorParser.className({ value: scopeClass }));
			}
		});
		selector.walkPseudos((node) => {
			if (node.value === ":root") {
				node.replaceWith(selectorParser.className({ value: scopeClass }));
			}
		});
		selector.walkTags((node) => {
			if (node.value === "html" || node.value === "body") {
				node.replaceWith(selectorParser.className({ value: scopeClass }));
			}
		});
		let containsScope = false;
		selector.walkClasses((node) => {
			if (node.value === scopeClass) containsScope = true;
		});
		if (!containsScope) {
			const zeroSpecificityScope = selectorParser.pseudo({ value: ":where" });
			zeroSpecificityScope.append(
				selectorParser.selector({
					nodes: [selectorParser.className({ value: scopeClass })],
				}),
			);
			selector.prepend(selectorParser.combinator({ value: " " }));
			selector.prepend(zeroSpecificityScope);
		}
	});
});

const scopeAndRenameCss = (source) => {
	const root = postcss.parse(source, { from: sourceCssPath });
	root.walkRules((rule) => {
		if (
			rule.parent?.type === "atrule" &&
			rule.parent.name.endsWith("keyframes")
		) {
			return;
		}
		rule.selector = transformSelector.processSync(rule.selector);
	});
	return root.toString();
};

const readExportedString = (source, name) => {
	const match = source.match(new RegExp(`export const ${name} = (.*);`));
	if (!match?.[1])
		throw new Error(`Could not read generated navbar field: ${name}`);
	return JSON.parse(match[1]);
};

const naturalizeMarkup = (markup) =>
	replaceTokens(markup, {
		...renameMap.classes,
		...renameMap.attributes,
	});

const renameMap = JSON.parse(await readFile(renameMapPath, "utf8"));
const [sourceCss, sourceData, sourceScript] = await Promise.all([
	readFile(sourceCssPath, "utf8"),
	readFile(sourceDataPath, "utf8"),
	readFile(sourceScriptPath, "utf8"),
]);

const dataFields = [
	"headerHtml",
	"productPortalHtml",
	"resourcesPortalHtml",
	"mobileDialogHtml",
];
const naturalizedData = [
	"// Generated by tools/naturalize-navbar.mjs from the gated source snapshot.",
	...dataFields.map(
		(name) =>
			`export const ${name} = ${JSON.stringify(naturalizeMarkup(readExportedString(sourceData, name)))};`,
	),
	"",
].join("\n");
const naturalizedScript = replaceTokens(sourceScript, renameMap.classes);

await Promise.all([
	mkdir(path.dirname(naturalizedCssPath), { recursive: true }),
	mkdir(path.dirname(naturalizedDataPath), { recursive: true }),
]);
await Promise.all([
	writeFile(naturalizedCssPath, scopeAndRenameCss(sourceCss)),
	writeFile(naturalizedDataPath, naturalizedData),
	writeFile(naturalizedScriptPath, naturalizedScript),
]);

console.log(
	JSON.stringify(
		{
			classesRenamed: Object.keys(renameMap.classes).length,
			attributesRenamed: Object.keys(renameMap.attributes).length,
			naturalizedCssPath,
			naturalizedDataPath,
			naturalizedScriptPath,
		},
		null,
		2,
	),
);
