const DASHBOARD_PATH = "/dashboard";
const DASHBOARD_GET_STARTED_LEGACY_PATH = `${DASHBOARD_PATH}/get-started`;
const GET_STARTED_PATH = "/get-started";
const TEAM_PATH = "/team";
const SETTINGS_ROOT_PATH = "/settings";
const SETTINGS_WORKSPACE_PATH = `${SETTINGS_ROOT_PATH}/workspace`;
const SETTINGS_INVITATIONS_PATH = `${SETTINGS_ROOT_PATH}/invitations`;
const SETTINGS_ACCOUNT_PATH = `${SETTINGS_ROOT_PATH}/account`;
const SETTINGS_CREATE_WORKSPACE_PATH = `${SETTINGS_ROOT_PATH}/create-workspace`;
const PRESET_BASELINE_PATH = "/__preset-baseline";
const CARD_REFERENCE_PATH = "/card-reference";
const WALK_IN_TEAM_CARD_PATH = "/walk-in-team-card";
const WRAPPED_PATH = "/wrapped";
const WRAPPED_FAMILY_PATH = "/wrapped-family";
const WRAPPED_FAMILY_MONEY_RAIN_PATH = `${WRAPPED_FAMILY_PATH}/money-rain`;

export const appRoutes = {
	home: () => DASHBOARD_PATH,
	dashboard: () => DASHBOARD_PATH,
	getStarted: () => GET_STARTED_PATH,
	dashboardGetStartedLegacy: () => DASHBOARD_GET_STARTED_LEGACY_PATH,
	team: () => TEAM_PATH,
	settings: () => SETTINGS_ROOT_PATH,
	settingsRoot: () => SETTINGS_ROOT_PATH,
	presetBaseline: () => PRESET_BASELINE_PATH,
	cardReference: () => CARD_REFERENCE_PATH,
	walkInTeamCard: () => WALK_IN_TEAM_CARD_PATH,
	wrapped: () => WRAPPED_PATH,
	wrappedFamily: () => WRAPPED_FAMILY_PATH,
	wrappedFamilyMoneyRain: () => WRAPPED_FAMILY_MONEY_RAIN_PATH,
	settingsWorkspace: () => SETTINGS_WORKSPACE_PATH,
	settingsInvitations: () => SETTINGS_INVITATIONS_PATH,
	settingsAccount: () => SETTINGS_ACCOUNT_PATH,
	settingsCreateWorkspace: () => SETTINGS_CREATE_WORKSPACE_PATH,
};
