import { schema, table } from "@chkit/core";

const rudel_wrapped_user_archetype_snapshots_v1 = table({
	database: "rudel",
	name: "wrapped_user_archetype_snapshots_v1",
	engine: "MergeTree",
	columns: [
		{ name: "snapshot_id", type: "String" },
		{ name: "snapshot_created_at", type: "DateTime64(3, 'UTC')" },
		{ name: "pipeline_version", type: "LowCardinality(String)" },
		{ name: "centroid_version", type: "LowCardinality(String)" },
		{ name: "scope", type: "LowCardinality(String)" },
		{ name: "organization_id", type: "String" },
		{ name: "user_id", type: "String" },
		{ name: "first_session_at", type: "DateTime64(3, 'UTC')" },
		{ name: "last_session_at", type: "DateTime64(3, 'UTC')" },
		{ name: "days_since_first_session", type: "UInt32" },
		{ name: "total_sessions", type: "UInt32" },
		{ name: "active_days", type: "UInt32" },
		{ name: "claude_session_count", type: "UInt32" },
		{ name: "codex_session_count", type: "UInt32" },
		{ name: "total_tokens", type: "UInt64" },
		{ name: "estimated_spend_usd", type: "Float64" },
		{ name: "mean_session_min", type: "Float64" },
		{ name: "longest_session_min", type: "UInt32" },
		{ name: "commit_sessions", type: "UInt32" },
		{ name: "distinct_repos", type: "UInt32", nullable: true },
		{ name: "breadth_available", type: "UInt8" },
		{ name: "range_entropy", type: "Float64" },
		{ name: "consistency_raw", type: "Float64" },
		{ name: "intensity_raw", type: "Float64" },
		{ name: "session_shape_raw", type: "Float64" },
		{ name: "cost_intensity_raw", type: "Float64" },
		{ name: "output_raw", type: "Float64" },
		{ name: "breadth_raw", type: "Float64", nullable: true },
		{ name: "range_raw", type: "Float64" },
		{ name: "consistency", type: "Float64" },
		{ name: "intensity", type: "Float64" },
		{ name: "session_shape", type: "Float64" },
		{ name: "cost_intensity", type: "Float64" },
		{ name: "output", type: "Float64" },
		{ name: "breadth", type: "Float64", nullable: true },
		{ name: "range", type: "Float64" },
		{ name: "archetype_id", type: "UInt8" },
		{ name: "archetype_key", type: "LowCardinality(String)" },
		{ name: "archetype_name", type: "String" },
		{ name: "archetype_distance", type: "Float64" },
		{ name: "archetype_distance_ratio_to_max", type: "Float64" },
	],
	primaryKey: [],
	orderBy: ["snapshot_id", "organization_id", "user_id"],
	partitionBy: "toYYYYMM(toDate(snapshot_created_at))",
});

const rudel_wrapped_user_archetype_runs_v1 = table({
	database: "rudel",
	name: "wrapped_user_archetype_runs_v1",
	engine: "MergeTree",
	columns: [
		{ name: "snapshot_id", type: "String" },
		{ name: "snapshot_created_at", type: "DateTime64(3, 'UTC')" },
		{ name: "pipeline_version", type: "LowCardinality(String)" },
		{ name: "centroid_version", type: "LowCardinality(String)" },
		{ name: "scope", type: "LowCardinality(String)" },
		{ name: "user_scope_count", type: "UInt32" },
		{ name: "trigger_reason", type: "LowCardinality(String)" },
		{ name: "trigger_source", type: "LowCardinality(Nullable(String))" },
		{ name: "trigger_session_id", type: "String", nullable: true },
	],
	primaryKey: [],
	orderBy: ["snapshot_created_at", "snapshot_id"],
});

export default schema(
	rudel_wrapped_user_archetype_snapshots_v1,
	rudel_wrapped_user_archetype_runs_v1,
);
