export type ModelPricingProvider = "anthropic" | "openai";

export type ModelContextBand = "base" | "long";

export type ModelRateCardEntry = {
	provider: ModelPricingProvider;
	model: string;
	displayName: string;
	match: readonly string[];
	effectiveFrom: string;
	effectiveTo?: string;
	contextBand: ModelContextBand;
	inputPerMTok: number;
	cacheReadPerMTok: number | null;
	cacheWrite5mPerMTok: number | null;
	cacheWrite1hPerMTok: number | null;
	outputPerMTok: number;
	source: string;
	verifiedAt: string;
	notes: string;
};

export const MODEL_RATE_CARD_VERSION = "2026-08-02";

// Standard first-party API rates in USD per million tokens. Keep rows grouped
// by provider and model family, with the newest effective period first.
export const MODEL_RATE_CARD: readonly ModelRateCardEntry[] = [
	// OpenAI: GPT-5.6
	{
		provider: "openai",
		model: "gpt-5.6-sol",
		displayName: "GPT-5.6 Sol",
		match: ["^gpt-5\\.6(?:-sol)?$"],
		effectiveFrom: "2026-06-12",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 30,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
		verifiedAt: "2026-08-02",
		notes:
			"Default tier; session aggregates cannot identify individual requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-sol",
		displayName: "GPT-5.6 Sol",
		match: ["^gpt-5\\.6(?:-sol)?$"],
		effectiveFrom: "2026-06-12",
		contextBand: "long",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: 12.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 45,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-terra",
		displayName: "GPT-5.6 Terra",
		match: ["^gpt-5\\.6-terra$"],
		effectiveFrom: "2026-06-12",
		contextBand: "base",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.2,
		cacheWrite5mPerMTok: 2.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 12,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
		verifiedAt: "2026-08-02",
		notes:
			"Default tier; session aggregates cannot identify individual requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-terra",
		displayName: "GPT-5.6 Terra",
		match: ["^gpt-5\\.6-terra$"],
		effectiveFrom: "2026-06-12",
		contextBand: "long",
		inputPerMTok: 4,
		cacheReadPerMTok: 0.4,
		cacheWrite5mPerMTok: 5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 18,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-luna",
		displayName: "GPT-5.6 Luna",
		match: ["^gpt-5\\.6-luna$"],
		effectiveFrom: "2026-06-12",
		contextBand: "base",
		inputPerMTok: 0.2,
		cacheReadPerMTok: 0.02,
		cacheWrite5mPerMTok: 0.25,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 1.2,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
		verifiedAt: "2026-08-02",
		notes:
			"Default tier; session aggregates cannot identify individual requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-luna",
		displayName: "GPT-5.6 Luna",
		match: ["^gpt-5\\.6-luna$"],
		effectiveFrom: "2026-06-12",
		contextBand: "long",
		inputPerMTok: 0.4,
		cacheReadPerMTok: 0.04,
		cacheWrite5mPerMTok: 0.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 1.8,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},

	// OpenAI: GPT-5.5
	{
		provider: "openai",
		model: "gpt-5.5",
		displayName: "GPT-5.5",
		match: ["^gpt-5\\.5(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 30,
		source: "https://developers.openai.com/api/docs/models/gpt-5.5",
		verifiedAt: "2026-08-02",
		notes:
			"Default tier; OpenAI does not publish a separate cache-write rate for this model.",
	},
	{
		provider: "openai",
		model: "gpt-5.5",
		displayName: "GPT-5.5",
		match: ["^gpt-5\\.5(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "long",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 45,
		source: "https://developers.openai.com/api/docs/models/gpt-5.5",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.5-pro",
		displayName: "GPT-5.5 Pro",
		match: ["^gpt-5\\.5-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "base",
		inputPerMTok: 30,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 180,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-02",
		notes: "Cached input pricing is not published for this model.",
	},
	{
		provider: "openai",
		model: "gpt-5.5-pro",
		displayName: "GPT-5.5 Pro",
		match: ["^gpt-5\\.5-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "long",
		inputPerMTok: 60,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 270,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},

	// OpenAI: GPT-5.4
	{
		provider: "openai",
		model: "gpt-5.4",
		displayName: "GPT-5.4",
		match: ["^gpt-5\\.4(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 2.5,
		cacheReadPerMTok: 0.25,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 15,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4",
		verifiedAt: "2026-04-08",
		notes:
			"Migrated from the legacy catalog; session aggregates default to the base context tier.",
	},
	{
		provider: "openai",
		model: "gpt-5.4",
		displayName: "GPT-5.4",
		match: ["^gpt-5\\.4(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "long",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 22.5,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-pro",
		displayName: "GPT-5.4 Pro",
		match: ["^gpt-5\\.4-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 30,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 180,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-pro",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog; cached input is not published.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-pro",
		displayName: "GPT-5.4 Pro",
		match: ["^gpt-5\\.4-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "long",
		inputPerMTok: 60,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 270,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-pro",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-mini",
		displayName: "GPT-5.4 Mini",
		match: ["^gpt-5\\.4-mini(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 0.75,
		cacheReadPerMTok: 0.075,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 4.5,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-mini",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-nano",
		displayName: "GPT-5.4 Nano",
		match: ["^gpt-5\\.4-nano(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 0.2,
		cacheReadPerMTok: 0.02,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 1.25,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-nano",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},

	// OpenAI: GPT-5.3 and legacy GPT-5.x Codex
	{
		provider: "openai",
		model: "gpt-5.3-chat-latest",
		displayName: "GPT-5.3 Chat",
		match: ["^gpt-5\\.3-chat-latest$"],
		effectiveFrom: "2026-02-05",
		contextBand: "base",
		inputPerMTok: 1.75,
		cacheReadPerMTok: 0.175,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 14,
		source: "https://developers.openai.com/api/docs/models/gpt-5.3-chat-latest",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.3-codex",
		displayName: "GPT-5.3 Codex",
		match: ["^gpt-5\\.3-codex$"],
		effectiveFrom: "2026-02-05",
		contextBand: "base",
		inputPerMTok: 1.75,
		cacheReadPerMTok: 0.175,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 14,
		source: "https://developers.openai.com/api/docs/models/gpt-5.3-codex",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-chat-latest",
		displayName: "GPT-5.1 Chat",
		match: ["^gpt-5(?:\\.1)?-chat-latest$"],
		effectiveFrom: "2025-11-13",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-chat-latest",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-codex-max",
		displayName: "GPT-5.1 Codex Max",
		match: ["^gpt-5(?:\\.1)?-codex-max$"],
		effectiveFrom: "2025-11-19",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-codex-max",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-codex-mini",
		displayName: "GPT-5.1 Codex Mini",
		match: ["^gpt-5(?:\\.1)?-codex-mini$"],
		effectiveFrom: "2025-11-13",
		contextBand: "base",
		inputPerMTok: 0.25,
		cacheReadPerMTok: 0.025,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 2,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-codex-mini",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-codex",
		displayName: "GPT-5 / GPT-5.1 Codex",
		match: ["^gpt-5(?:\\.1)?-codex$"],
		effectiveFrom: "2025-09-15",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-codex-max",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},

	// Anthropic: Claude 5 and Claude Opus 4.x
	{
		provider: "anthropic",
		model: "claude-fable-5",
		displayName: "Claude Fable 5",
		match: ["^claude-fable-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-06-09",
		contextBand: "base",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: 12.5,
		cacheWrite1hPerMTok: 20,
		outputPerMTok: 50,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-mythos-5",
		displayName: "Claude Mythos 5",
		match: ["^claude-mythos-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-06-09",
		contextBand: "base",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: 12.5,
		cacheWrite1hPerMTok: 20,
		outputPerMTok: 50,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "Limited availability; the full 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-5",
		displayName: "Claude Opus 5",
		match: ["^claude-opus-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-07-24",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-8",
		displayName: "Claude Opus 4.8",
		match: ["^claude-opus-4-8(?:-\\d{8})?$"],
		effectiveFrom: "2026-05-28",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-7",
		displayName: "Claude Opus 4.7",
		match: ["^claude-opus-4-7(?:-\\d{8})?$"],
		effectiveFrom: "2026-04-16",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-6",
		displayName: "Claude Opus 4.6",
		match: ["^claude-opus-4-6(?:-\\d{8})?$"],
		effectiveFrom: "2026-02-05",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog; 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-5-20251101",
		displayName: "Claude Opus 4.5",
		match: ["^claude-opus-4-5(?:-\\d{8})?$"],
		effectiveFrom: "2025-11-24",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-1-20250805",
		displayName: "Claude Opus 4.1",
		match: ["^claude-opus-4-1(?:-\\d{8})?$"],
		effectiveFrom: "2025-08-05",
		contextBand: "base",
		inputPerMTok: 15,
		cacheReadPerMTok: 1.5,
		cacheWrite5mPerMTok: 18.75,
		cacheWrite1hPerMTok: 30,
		outputPerMTok: 75,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-20250514",
		displayName: "Claude Opus 4",
		match: ["^claude-opus-4(?:-\\d{8})?$"],
		effectiveFrom: "2025-05-22",
		contextBand: "base",
		inputPerMTok: 15,
		cacheReadPerMTok: 1.5,
		cacheWrite5mPerMTok: 18.75,
		cacheWrite1hPerMTok: 30,
		outputPerMTok: 75,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},

	// Anthropic: Claude Sonnet and Haiku
	{
		provider: "anthropic",
		model: "claude-sonnet-5",
		displayName: "Claude Sonnet 5",
		match: ["^claude-sonnet-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-09-01",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "Published follow-on rate; the full 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-5",
		displayName: "Claude Sonnet 5",
		match: ["^claude-sonnet-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-06-30",
		effectiveTo: "2026-08-31",
		contextBand: "base",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.2,
		cacheWrite5mPerMTok: 2.5,
		cacheWrite1hPerMTok: 4,
		outputPerMTok: 10,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes:
			"Introductory rate through August 31, 2026; the full 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-4-6",
		displayName: "Claude Sonnet 4.6",
		match: ["^claude-sonnet-4-6(?:-\\d{8})?$"],
		effectiveFrom: "2026-02-17",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog; 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-4-5-20250929",
		displayName: "Claude Sonnet 4.5",
		match: ["^claude-sonnet-4-5(?:-\\d{8})?$"],
		effectiveFrom: "2025-09-29",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-4-20250514",
		displayName: "Claude Sonnet 4",
		match: ["^claude-sonnet-4(?:-\\d{8})?$"],
		effectiveFrom: "2025-05-22",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-7-sonnet-20250219",
		displayName: "Claude Sonnet 3.7",
		match: ["^claude-(?:3-7-sonnet|sonnet-3-7)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2025-02-24",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-haiku-4-5-20251001",
		displayName: "Claude Haiku 4.5",
		match: ["^claude-haiku-4-5(?:-\\d{8})?$"],
		effectiveFrom: "2025-10-15",
		contextBand: "base",
		inputPerMTok: 1,
		cacheReadPerMTok: 0.1,
		cacheWrite5mPerMTok: 1.25,
		cacheWrite1hPerMTok: 2,
		outputPerMTok: 5,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-5-haiku-20241022",
		displayName: "Claude Haiku 3.5",
		match: ["^claude-(?:3-5-haiku|haiku-3-5)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2024-10-22",
		contextBand: "base",
		inputPerMTok: 0.8,
		cacheReadPerMTok: 0.08,
		cacheWrite5mPerMTok: 1,
		cacheWrite1hPerMTok: 1.6,
		outputPerMTok: 4,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-opus-20240229",
		displayName: "Claude Opus 3",
		match: ["^claude-(?:3-opus|opus-3)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2024-03-04",
		contextBand: "base",
		inputPerMTok: 15,
		cacheReadPerMTok: 1.5,
		cacheWrite5mPerMTok: 18.75,
		cacheWrite1hPerMTok: 30,
		outputPerMTok: 75,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-haiku-20240307",
		displayName: "Claude Haiku 3",
		match: ["^claude-(?:3-haiku|haiku-3)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2024-03-13",
		contextBand: "base",
		inputPerMTok: 0.25,
		cacheReadPerMTok: 0.03,
		cacheWrite5mPerMTok: 0.3,
		cacheWrite1hPerMTok: 0.5,
		outputPerMTok: 1.25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes:
			"Migrated from the legacy catalog; preserves its rounded $0.30 5m write rate, with 1h at the published 2x base multiplier.",
	},
];
