export type ModelPricingProvider = "anthropic" | "openai";

export type ModelContextBand = "base" | "long";

export const MODEL_LONG_CONTEXT_THRESHOLD_TOKENS = 272_000;

export type ModelRateCardEntry = {
	provider: ModelPricingProvider;
	model: string;
	displayName: string;
	match: readonly string[];
	effectiveFrom: string;
	effectiveTo?: string;
	contextBand: ModelContextBand;
	inputPerMTok: number;
	cacheReadPerMTok: number | null;
	cacheWrite5mPerMTok: number | null;
	cacheWrite1hPerMTok: number | null;
	outputPerMTok: number;
	source: string;
	verifiedAt: string;
	notes: string;
};

export type ModelRateModifierDimension =
	| "service_tier"
	| "inference_speed"
	| "inference_geo";

export type ModelRateModifierEntry = {
	provider: ModelPricingProvider;
	model: string;
	dimension: ModelRateModifierDimension;
	values: readonly string[];
	effectiveFrom: string;
	effectiveTo?: string;
	contextBand?: ModelContextBand;
	multiplier: number;
	source: string;
	verifiedAt: string;
	notes: string;
};

export type UnpricedModelIdentity = {
	provider: ModelPricingProvider;
	model: string;
	match: readonly string[];
	reason: "no_public_rate" | "provider_mapping_required";
	source: string;
	verifiedAt: string;
	notes: string;
};

export const MODEL_RATE_CARD_VERSION = "2026-08-05";

// Standard first-party API rates in USD per million tokens. Keep rows grouped
// by provider and model family, with the newest effective period first.
export const MODEL_RATE_CARD: readonly ModelRateCardEntry[] = [
	// OpenAI: GPT-5.6
	{
		provider: "openai",
		model: "gpt-5.6-sol",
		displayName: "GPT-5.6 Sol",
		match: ["^gpt-5\\.6(?:-sol)?$"],
		effectiveFrom: "2026-06-26",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 30,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
		verifiedAt: "2026-08-02",
		notes: "Default processing tier; request context selects the long band.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-sol",
		displayName: "GPT-5.6 Sol",
		match: ["^gpt-5\\.6(?:-sol)?$"],
		effectiveFrom: "2026-06-26",
		contextBand: "long",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: 12.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 45,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-terra",
		displayName: "GPT-5.6 Terra",
		match: ["^gpt-5\\.6-terra$"],
		effectiveFrom: "2026-07-30",
		contextBand: "base",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.2,
		cacheWrite5mPerMTok: 2.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 12,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
		verifiedAt: "2026-08-02",
		notes: "Default processing tier; request context selects the long band.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-terra",
		displayName: "GPT-5.6 Terra",
		match: ["^gpt-5\\.6-terra$"],
		effectiveFrom: "2026-07-30",
		contextBand: "long",
		inputPerMTok: 4,
		cacheReadPerMTok: 0.4,
		cacheWrite5mPerMTok: 5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 18,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-terra",
		displayName: "GPT-5.6 Terra",
		match: ["^gpt-5\\.6-terra$"],
		effectiveFrom: "2026-06-26",
		effectiveTo: "2026-07-29",
		contextBand: "base",
		inputPerMTok: 2.5,
		cacheReadPerMTok: 0.25,
		cacheWrite5mPerMTok: 3.125,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 15,
		source:
			"https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6/",
		verifiedAt: "2026-08-05",
		notes: "Initial public-preview rate before the July 30 reduction.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-terra",
		displayName: "GPT-5.6 Terra",
		match: ["^gpt-5\\.6-terra$"],
		effectiveFrom: "2026-06-26",
		effectiveTo: "2026-07-29",
		contextBand: "long",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 22.5,
		source:
			"https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6/",
		verifiedAt: "2026-08-05",
		notes: "Initial public-preview long-context rate before July 30.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-luna",
		displayName: "GPT-5.6 Luna",
		match: ["^gpt-5\\.6-luna$"],
		effectiveFrom: "2026-07-30",
		contextBand: "base",
		inputPerMTok: 0.2,
		cacheReadPerMTok: 0.02,
		cacheWrite5mPerMTok: 0.25,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 1.2,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
		verifiedAt: "2026-08-02",
		notes: "Default processing tier; request context selects the long band.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-luna",
		displayName: "GPT-5.6 Luna",
		match: ["^gpt-5\\.6-luna$"],
		effectiveFrom: "2026-07-30",
		contextBand: "long",
		inputPerMTok: 0.4,
		cacheReadPerMTok: 0.04,
		cacheWrite5mPerMTok: 0.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 1.8,
		source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-luna",
		displayName: "GPT-5.6 Luna",
		match: ["^gpt-5\\.6-luna$"],
		effectiveFrom: "2026-06-26",
		effectiveTo: "2026-07-29",
		contextBand: "base",
		inputPerMTok: 1,
		cacheReadPerMTok: 0.1,
		cacheWrite5mPerMTok: 1.25,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 6,
		source:
			"https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6/",
		verifiedAt: "2026-08-05",
		notes: "Initial public-preview rate before the July 30 reduction.",
	},
	{
		provider: "openai",
		model: "gpt-5.6-luna",
		displayName: "GPT-5.6 Luna",
		match: ["^gpt-5\\.6-luna$"],
		effectiveFrom: "2026-06-26",
		effectiveTo: "2026-07-29",
		contextBand: "long",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.2,
		cacheWrite5mPerMTok: 2.5,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 9,
		source:
			"https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6/",
		verifiedAt: "2026-08-05",
		notes: "Initial public-preview long-context rate before July 30.",
	},

	// OpenAI: GPT-5.5
	{
		provider: "openai",
		model: "gpt-5.5",
		displayName: "GPT-5.5",
		match: ["^gpt-5\\.5(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 30,
		source: "https://developers.openai.com/api/docs/models/gpt-5.5",
		verifiedAt: "2026-08-02",
		notes:
			"Default tier; OpenAI does not publish a separate cache-write rate for this model.",
	},
	{
		provider: "openai",
		model: "gpt-5.5",
		displayName: "GPT-5.5",
		match: ["^gpt-5\\.5(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "long",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 45,
		source: "https://developers.openai.com/api/docs/models/gpt-5.5",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.5-pro",
		displayName: "GPT-5.5 Pro",
		match: ["^gpt-5\\.5-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "base",
		inputPerMTok: 30,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 180,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-02",
		notes: "Cached input pricing is not published for this model.",
	},
	{
		provider: "openai",
		model: "gpt-5.5-pro",
		displayName: "GPT-5.5 Pro",
		match: ["^gpt-5\\.5-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-04-23",
		contextBand: "long",
		inputPerMTok: 60,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 270,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},

	// OpenAI: GPT-5.4
	{
		provider: "openai",
		model: "gpt-5.4",
		displayName: "GPT-5.4",
		match: ["^gpt-5\\.4(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 2.5,
		cacheReadPerMTok: 0.25,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 15,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4",
		verifiedAt: "2026-04-08",
		notes: "Default processing tier; request context selects the long band.",
	},
	{
		provider: "openai",
		model: "gpt-5.4",
		displayName: "GPT-5.4",
		match: ["^gpt-5\\.4(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "long",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 22.5,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-pro",
		displayName: "GPT-5.4 Pro",
		match: ["^gpt-5\\.4-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 30,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 180,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-pro",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog; cached input is not published.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-pro",
		displayName: "GPT-5.4 Pro",
		match: ["^gpt-5\\.4-pro(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "long",
		inputPerMTok: 60,
		cacheReadPerMTok: null,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 270,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-pro",
		verifiedAt: "2026-08-02",
		notes: "Published tier for requests above 272k input tokens.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-mini",
		displayName: "GPT-5.4 Mini",
		match: ["^gpt-5\\.4-mini(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-17",
		contextBand: "base",
		inputPerMTok: 0.75,
		cacheReadPerMTok: 0.075,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 4.5,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-mini",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.4-nano",
		displayName: "GPT-5.4 Nano",
		match: ["^gpt-5\\.4-nano(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2026-03-05",
		contextBand: "base",
		inputPerMTok: 0.2,
		cacheReadPerMTok: 0.02,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 1.25,
		source: "https://developers.openai.com/api/docs/models/gpt-5.4-nano",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},

	// OpenAI: native Codex history
	{
		provider: "openai",
		model: "o3",
		displayName: "o3",
		match: ["^o3(?:-2025-04-16)?$"],
		effectiveFrom: "2025-04-16",
		effectiveTo: "2025-06-09",
		contextBand: "base",
		inputPerMTok: 10,
		cacheReadPerMTok: 2.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 40,
		source: "https://openai.com/index/introducing-o3-and-o4-mini/",
		verifiedAt: "2026-08-05",
		notes: "Original Codex CLI launch rate.",
	},
	{
		provider: "openai",
		model: "o3",
		displayName: "o3",
		match: ["^o3(?:-2025-04-16)?$"],
		effectiveFrom: "2025-06-10",
		contextBand: "base",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 8,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-05",
		notes: "Reduced standard API rate effective June 10, 2025.",
	},
	{
		provider: "openai",
		model: "o4-mini",
		displayName: "o4-mini",
		match: ["^o4-mini(?:-2025-04-16)?$"],
		effectiveFrom: "2025-04-16",
		contextBand: "base",
		inputPerMTok: 1.1,
		cacheReadPerMTok: 0.275,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 4.4,
		source: "https://openai.com/index/introducing-o3-and-o4-mini/",
		verifiedAt: "2026-08-05",
		notes: "Original Codex CLI default model.",
	},
	{
		provider: "openai",
		model: "gpt-4.1",
		displayName: "GPT-4.1",
		match: ["^gpt-4\\.1(?:-2025-04-14)?$"],
		effectiveFrom: "2025-04-16",
		contextBand: "base",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 8,
		source: "https://openai.com/index/gpt-4-1/",
		verifiedAt: "2026-08-05",
		notes: "Exact alias and launch snapshot supported by Codex.",
	},
	{
		provider: "openai",
		model: "codex-mini-latest",
		displayName: "Codex Mini",
		match: ["^codex-mini-latest$"],
		effectiveFrom: "2025-05-16",
		effectiveTo: "2026-02-12",
		contextBand: "base",
		inputPerMTok: 1.5,
		cacheReadPerMTok: 0.375,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 6,
		source: "https://openai.com/index/introducing-codex/",
		verifiedAt: "2026-08-05",
		notes: "Native Codex model until its documented shutdown.",
	},
	{
		provider: "openai",
		model: "gpt-5",
		displayName: "GPT-5",
		match: ["^gpt-5(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2025-08-07",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-05",
		notes: "Plain and dated GPT-5 API identities.",
	},
	{
		provider: "openai",
		model: "gpt-5-codex",
		displayName: "GPT-5 Codex",
		match: ["^gpt-5-codex$"],
		effectiveFrom: "2025-09-23",
		effectiveTo: "2026-07-23",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/deprecations",
		verifiedAt: "2026-08-05",
		notes: "API comparability starts after the Codex product launch.",
	},
	{
		provider: "openai",
		model: "gpt-5.1",
		displayName: "GPT-5.1",
		match: ["^gpt-5\\.1(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2025-11-13",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-05",
		notes: "Plain and dated GPT-5.1 API identities.",
	},
	{
		provider: "openai",
		model: "gpt-5.2",
		displayName: "GPT-5.2",
		match: ["^gpt-5\\.2(?:-\\d{4}-\\d{2}-\\d{2})?$"],
		effectiveFrom: "2025-12-11",
		contextBand: "base",
		inputPerMTok: 1.75,
		cacheReadPerMTok: 0.175,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 14,
		source: "https://developers.openai.com/api/docs/pricing",
		verifiedAt: "2026-08-05",
		notes: "Native Codex catalog model.",
	},
	{
		provider: "openai",
		model: "gpt-5.2-codex",
		displayName: "GPT-5.2 Codex",
		match: ["^gpt-5\\.2-codex$"],
		effectiveFrom: "2025-12-18",
		effectiveTo: "2026-07-23",
		contextBand: "base",
		inputPerMTok: 1.75,
		cacheReadPerMTok: 0.175,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 14,
		source: "https://developers.openai.com/api/docs/deprecations",
		verifiedAt: "2026-08-05",
		notes: "Exact Codex model API window.",
	},

	// OpenAI: GPT-5.3 and later Codex
	{
		provider: "openai",
		model: "gpt-5.3-chat-latest",
		displayName: "GPT-5.3 Chat",
		match: ["^gpt-5\\.3-chat-latest$"],
		effectiveFrom: "2026-02-05",
		contextBand: "base",
		inputPerMTok: 1.75,
		cacheReadPerMTok: 0.175,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 14,
		source: "https://developers.openai.com/api/docs/models/gpt-5.3-chat-latest",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.3-codex",
		displayName: "GPT-5.3 Codex",
		match: ["^gpt-5\\.3-codex$"],
		effectiveFrom: "2026-02-05",
		contextBand: "base",
		inputPerMTok: 1.75,
		cacheReadPerMTok: 0.175,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 14,
		source: "https://developers.openai.com/api/docs/models/gpt-5.3-codex",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-chat-latest",
		displayName: "GPT-5.1 Chat",
		match: ["^gpt-5\\.1-chat-latest$"],
		effectiveFrom: "2025-11-13",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-chat-latest",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-codex-max",
		displayName: "GPT-5.1 Codex Max",
		match: ["^gpt-5\\.1-codex-max$"],
		effectiveFrom: "2025-11-19",
		effectiveTo: "2026-07-23",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-codex-max",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-codex-mini",
		displayName: "GPT-5.1 Codex Mini",
		match: ["^gpt-5\\.1-codex-mini$"],
		effectiveFrom: "2025-11-13",
		effectiveTo: "2026-07-23",
		contextBand: "base",
		inputPerMTok: 0.25,
		cacheReadPerMTok: 0.025,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 2,
		source: "https://developers.openai.com/api/docs/models/gpt-5.1-codex-mini",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "openai",
		model: "gpt-5.1-codex",
		displayName: "GPT-5.1 Codex",
		match: ["^gpt-5\\.1-codex$"],
		effectiveFrom: "2025-11-13",
		effectiveTo: "2026-07-23",
		contextBand: "base",
		inputPerMTok: 1.25,
		cacheReadPerMTok: 0.125,
		cacheWrite5mPerMTok: null,
		cacheWrite1hPerMTok: null,
		outputPerMTok: 10,
		source: "https://developers.openai.com/api/docs/deprecations",
		verifiedAt: "2026-08-05",
		notes: "Exact GPT-5.1 Codex API window.",
	},

	// Anthropic: Claude 5 and Claude Opus 4.x
	{
		provider: "anthropic",
		model: "claude-fable-5",
		displayName: "Claude Fable 5",
		match: ["^claude-fable-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-06-09",
		contextBand: "base",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: 12.5,
		cacheWrite1hPerMTok: 20,
		outputPerMTok: 50,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-mythos-5",
		displayName: "Claude Mythos 5",
		match: ["^claude-mythos-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-06-09",
		contextBand: "base",
		inputPerMTok: 10,
		cacheReadPerMTok: 1,
		cacheWrite5mPerMTok: 12.5,
		cacheWrite1hPerMTok: 20,
		outputPerMTok: 50,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "Limited availability; the full 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-5",
		displayName: "Claude Opus 5",
		match: ["^claude-opus-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-07-24",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-8",
		displayName: "Claude Opus 4.8",
		match: ["^claude-opus-4-8(?:-\\d{8})?$"],
		effectiveFrom: "2026-05-28",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-7",
		displayName: "Claude Opus 4.7",
		match: ["^claude-opus-4-7(?:-\\d{8})?$"],
		effectiveFrom: "2026-04-16",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "The full 1M context window is billed at the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-6",
		displayName: "Claude Opus 4.6",
		match: ["^claude-opus-4-6(?:-\\d{8})?$"],
		effectiveFrom: "2026-02-05",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog; 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-5-20251101",
		displayName: "Claude Opus 4.5",
		match: ["^claude-opus-4-5(?:-\\d{8})?$"],
		effectiveFrom: "2025-11-24",
		contextBand: "base",
		inputPerMTok: 5,
		cacheReadPerMTok: 0.5,
		cacheWrite5mPerMTok: 6.25,
		cacheWrite1hPerMTok: 10,
		outputPerMTok: 25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-1-20250805",
		displayName: "Claude Opus 4.1",
		match: ["^claude-opus-4-1(?:-\\d{8})?$"],
		effectiveFrom: "2025-08-05",
		effectiveTo: "2026-08-05",
		contextBand: "base",
		inputPerMTok: 15,
		cacheReadPerMTok: 1.5,
		cacheWrite5mPerMTok: 18.75,
		cacheWrite1hPerMTok: 30,
		outputPerMTok: 75,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-20250514",
		displayName: "Claude Opus 4",
		match: ["^claude-opus-4(?:-\\d{8})?$"],
		effectiveFrom: "2025-05-22",
		effectiveTo: "2026-06-15",
		contextBand: "base",
		inputPerMTok: 15,
		cacheReadPerMTok: 1.5,
		cacheWrite5mPerMTok: 18.75,
		cacheWrite1hPerMTok: 30,
		outputPerMTok: 75,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},

	// Anthropic: Claude Sonnet and Haiku
	{
		provider: "anthropic",
		model: "claude-sonnet-5",
		displayName: "Claude Sonnet 5",
		match: ["^claude-sonnet-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-09-01",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes: "Published follow-on rate; the full 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-5",
		displayName: "Claude Sonnet 5",
		match: ["^claude-sonnet-5(?:-\\d{8})?$"],
		effectiveFrom: "2026-06-30",
		effectiveTo: "2026-08-31",
		contextBand: "base",
		inputPerMTok: 2,
		cacheReadPerMTok: 0.2,
		cacheWrite5mPerMTok: 2.5,
		cacheWrite1hPerMTok: 4,
		outputPerMTok: 10,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-08-02",
		notes:
			"Introductory rate through August 31, 2026; the full 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-4-6",
		displayName: "Claude Sonnet 4.6",
		match: ["^claude-sonnet-4-6(?:-\\d{8})?$"],
		effectiveFrom: "2026-02-17",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog; 1M context uses the base rate.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-4-5-20250929",
		displayName: "Claude Sonnet 4.5",
		match: ["^claude-sonnet-4-5(?:-\\d{8})?$"],
		effectiveFrom: "2025-09-29",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-sonnet-4-20250514",
		displayName: "Claude Sonnet 4",
		match: ["^claude-sonnet-4(?:-\\d{8})?$"],
		effectiveFrom: "2025-05-22",
		effectiveTo: "2026-06-15",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-5-sonnet-20240620",
		displayName: "Claude Sonnet 3.5 (June)",
		match: ["^claude-3-5-sonnet-20240620$"],
		effectiveFrom: "2025-02-24",
		effectiveTo: "2025-10-28",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://www.anthropic.com/news/claude-3-5-sonnet",
		verifiedAt: "2026-08-05",
		notes: "Exact first-party snapshot and Claude Code-relevant window.",
	},
	{
		provider: "anthropic",
		model: "claude-3-5-sonnet-20241022",
		displayName: "Claude Sonnet 3.5 (October)",
		match: ["^claude-3-5-sonnet-20241022$"],
		effectiveFrom: "2025-02-24",
		effectiveTo: "2025-10-28",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://www.anthropic.com/news/claude-3-5-sonnet",
		verifiedAt: "2026-08-05",
		notes: "Exact first-party snapshot and retirement bound.",
	},
	{
		provider: "anthropic",
		model: "claude-3-sonnet-20240229",
		displayName: "Claude Sonnet 3",
		match: ["^claude-3-sonnet-20240229$"],
		effectiveFrom: "2025-02-24",
		effectiveTo: "2025-07-21",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source:
			"https://platform.claude.com/docs/en/about-claude/model-deprecations",
		verifiedAt: "2026-08-05",
		notes: "Exact first-party snapshot selectable by Claude Code.",
	},
	{
		provider: "anthropic",
		model: "claude-3-7-sonnet-20250219",
		displayName: "Claude Sonnet 3.7",
		match: ["^claude-(?:3-7-sonnet|sonnet-3-7)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2025-02-24",
		effectiveTo: "2026-02-19",
		contextBand: "base",
		inputPerMTok: 3,
		cacheReadPerMTok: 0.3,
		cacheWrite5mPerMTok: 3.75,
		cacheWrite1hPerMTok: 6,
		outputPerMTok: 15,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-haiku-4-5-20251001",
		displayName: "Claude Haiku 4.5",
		match: ["^claude-haiku-4-5(?:-\\d{8})?$"],
		effectiveFrom: "2025-10-15",
		contextBand: "base",
		inputPerMTok: 1,
		cacheReadPerMTok: 0.1,
		cacheWrite5mPerMTok: 1.25,
		cacheWrite1hPerMTok: 2,
		outputPerMTok: 5,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-5-haiku-20241022",
		displayName: "Claude Haiku 3.5",
		match: ["^claude-(?:3-5-haiku|haiku-3-5)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2024-10-22",
		effectiveTo: "2026-02-19",
		contextBand: "base",
		inputPerMTok: 0.8,
		cacheReadPerMTok: 0.08,
		cacheWrite5mPerMTok: 1,
		cacheWrite1hPerMTok: 1.6,
		outputPerMTok: 4,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-opus-20240229",
		displayName: "Claude Opus 3",
		match: ["^claude-(?:3-opus|opus-3)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2024-03-04",
		effectiveTo: "2026-01-05",
		contextBand: "base",
		inputPerMTok: 15,
		cacheReadPerMTok: 1.5,
		cacheWrite5mPerMTok: 18.75,
		cacheWrite1hPerMTok: 30,
		outputPerMTok: 75,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes: "Migrated from the legacy catalog.",
	},
	{
		provider: "anthropic",
		model: "claude-3-haiku-20240307",
		displayName: "Claude Haiku 3",
		match: ["^claude-(?:3-haiku|haiku-3)(?:-latest|-\\d{8})?$"],
		effectiveFrom: "2024-03-13",
		effectiveTo: "2026-04-20",
		contextBand: "base",
		inputPerMTok: 0.25,
		cacheReadPerMTok: 0.03,
		cacheWrite5mPerMTok: 0.3,
		cacheWrite1hPerMTok: 0.5,
		outputPerMTok: 1.25,
		source: "https://platform.claude.com/docs/en/about-claude/pricing",
		verifiedAt: "2026-04-08",
		notes:
			"Migrated from the legacy catalog; preserves its rounded $0.30 5m write rate, with 1h at the published 2x base multiplier.",
	},
];

// Known native identities that deliberately have no comparable first-party API
// rate. Keeping them beside the rate card separates model identity from
// priceability without inventing a second evidence source.
export const MODEL_UNPRICED_IDENTITIES: readonly UnpricedModelIdentity[] = [
	{
		provider: "openai",
		model: "gpt-5.3-codex-spark",
		match: ["^gpt-5\\.3-codex-spark$"],
		reason: "no_public_rate",
		source: "https://learn.chatgpt.com/docs/models",
		verifiedAt: "2026-08-05",
		notes: "Codex research preview without public API access or API rates.",
	},
	{
		provider: "openai",
		model: "codex-auto-review",
		match: ["^codex-auto-review$"],
		reason: "provider_mapping_required",
		source: "https://github.com/openai/codex/tree/main/codex-rs/models-manager",
		verifiedAt: "2026-08-05",
		notes: "Client profile whose underlying dated model is not attested.",
	},
	{
		provider: "openai",
		model: "gpt-5-codex-mini",
		match: ["^gpt-5-codex-mini$"],
		reason: "no_public_rate",
		source: "https://learn.chatgpt.com/docs/models",
		verifiedAt: "2026-08-05",
		notes: "No sufficiently pinned public request-level API rate.",
	},
	{
		provider: "openai",
		model: "codex-1",
		match: ["^codex-1$"],
		reason: "no_public_rate",
		source: "https://openai.com/index/introducing-codex/",
		verifiedAt: "2026-08-05",
		notes: "Codex cloud model without a public request-level API rate.",
	},
];

// Price-changing response dimensions. Base/standard values are handled by the
// resolver; a non-base value must match one of these dated rules or it is
// unpriced. Multipliers apply independently to every published token class.
export const MODEL_RATE_MODIFIERS: readonly ModelRateModifierEntry[] = [
	...[
		["gpt-5.4", "2026-03-05", 2],
		["gpt-5.4-mini", "2026-03-17", 2],
		["gpt-5.5", "2026-04-24", 2.5],
		["gpt-5.6-sol", "2026-06-26", 2],
		["gpt-5.6-terra", "2026-06-26", 2],
		["gpt-5.6-luna", "2026-06-26", 2],
	].map(
		([model, effectiveFrom, multiplier]): ModelRateModifierEntry => ({
			provider: "openai",
			model: String(model),
			dimension: "service_tier",
			values: ["fast", "priority"],
			effectiveFrom: String(effectiveFrom),
			contextBand: "base",
			multiplier: Number(multiplier),
			source: "https://developers.openai.com/api/docs/pricing",
			verifiedAt: "2026-08-05",
			notes: "Published API Fast/Priority processing rate.",
		}),
	),
	{
		provider: "anthropic",
		model: "claude-opus-4-6",
		dimension: "inference_speed",
		values: ["fast"],
		effectiveFrom: "2026-02-07",
		effectiveTo: "2026-06-28",
		multiplier: 6,
		source: "https://platform.claude.com/docs/en/release-notes/overview",
		verifiedAt: "2026-08-05",
		notes: "Original $30/$150 Fast mode before removal.",
	},
	{
		provider: "anthropic",
		model: "claude-opus-4-7",
		dimension: "inference_speed",
		values: ["fast"],
		effectiveFrom: "2026-05-12",
		effectiveTo: "2026-07-23",
		multiplier: 6,
		source: "https://platform.claude.com/docs/en/release-notes/overview",
		verifiedAt: "2026-08-05",
		notes: "$30/$150 Fast mode before removal.",
	},
	...[
		["claude-opus-4-8", "2026-06-15"],
		["claude-opus-5", "2026-07-24"],
	].map(
		([model, effectiveFrom]): ModelRateModifierEntry => ({
			provider: "anthropic",
			model: String(model),
			dimension: "inference_speed",
			values: ["fast"],
			effectiveFrom: String(effectiveFrom),
			multiplier: 2,
			source: "https://platform.claude.com/docs/en/build-with-claude/fast-mode",
			verifiedAt: "2026-08-05",
			notes: "Published $10/$50 Fast mode; cache multipliers stack.",
		}),
	),
	...[
		["claude-opus-4-6", "2026-02-05"],
		["claude-sonnet-4-6", "2026-02-17"],
		["claude-opus-4-7", "2026-04-16"],
		["claude-opus-4-8", "2026-05-28"],
		["claude-fable-5", "2026-06-09"],
		["claude-mythos-5", "2026-06-09"],
		["claude-sonnet-5", "2026-06-30"],
		["claude-opus-5", "2026-07-24"],
	].map(
		([model, effectiveFrom]): ModelRateModifierEntry => ({
			provider: "anthropic",
			model: String(model),
			dimension: "inference_geo",
			values: ["us"],
			effectiveFrom: String(effectiveFrom),
			multiplier: 1.1,
			source: "https://platform.claude.com/docs/en/about-claude/pricing",
			verifiedAt: "2026-08-05",
			notes: "Anthropic US-only inference premium; all token classes stack.",
		}),
	),
];
