import type { Scenario } from "./types.js";

export const STUB_BASE_PLACEHOLDER = "{stubBase}";

export const SCENARIOS: readonly Scenario[] = [
	{
		name: "picker-real",
		label: "Real project picker",
		description:
			"Real local Claude and Codex sessions with mirrored account labels.",
		group: "Happy paths",
		profile: "local-real",
		argv: ["upload"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-real-to-stub",
		label: "Real data → stub",
		description:
			"Select real projects and send only to the loopback ingest stub.",
		group: "Happy paths",
		profile: "local-real",
		argv: ["upload"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "whoami-real",
		label: "Mirrored identity",
		description:
			"Show the cached real display identity through the local stub.",
		group: "States",
		profile: "local-real",
		argv: ["whoami"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "set-org-real",
		label: "Real organization picker",
		description:
			"Pick from mirrored organizations; persist only to sandbox state.",
		group: "States",
		profile: "local-real",
		argv: ["set-org"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "list-sessions-real",
		label: "Real session tree",
		description: "Compare the debug grouping against the interactive picker.",
		group: "States",
		profile: "local-real",
		argv: ["dev", "list-sessions"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "enable-real-sandboxed",
		label: "Enable with real reads",
		description:
			"Read real sessions while writing hooks only to the fake agent home.",
		group: "States",
		profile: "local-real",
		argv: ["enable"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "disable-real-sandboxed",
		label: "Disable sandboxed hooks",
		description:
			"Remove pre-seeded hooks without touching real agent configuration.",
		group: "States",
		profile: "local-real",
		argv: ["disable"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "hooks-enabled",
	},
	{
		name: "picker-happy",
		label: "Fixture picker",
		description:
			"Mixed Claude/Codex projects with varied ages and session counts.",
		group: "Happy paths",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-ok",
		label: "Successful upload",
		description: "A normal project selection and successful batch upload.",
		group: "Happy paths",
		profile: "fixture",
		argv: ["upload", "--endpoint", `${STUB_BASE_PLACEHOLDER}/rpc`],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "login",
		label: "Device login",
		description: "Complete the no-browser device flow entirely on loopback.",
		group: "Happy paths",
		profile: "fixture",
		argv: ["login", "--api-base", STUB_BASE_PLACEHOLDER, "--no-browser"],
		stubBehavior: "ok",
		env: {},
		fixture: "signed-out",
		agentState: "clean",
	},
	{
		name: "picker-empty",
		label: "Empty picker",
		description: "No discoverable Claude or Codex sessions.",
		group: "States",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "ok",
		env: {},
		fixture: "empty",
		agentState: "clean",
	},
	{
		name: "picker-huge",
		label: "200 projects",
		description: "Stress the flat picker with 200 projects and long paths.",
		group: "Scale",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "ok",
		env: {},
		fixture: "huge",
		agentState: "clean",
	},
	{
		name: "upload-staggered-progress",
		label: "Staggered progress",
		description:
			"Uploads finish between 200 ms and 8 s so progress visibly advances.",
		group: "Scale",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "staggered",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-rate-limit",
		label: "429 rate limit",
		description: "Terminal 429 with Retry-After and retry-queue persistence.",
		group: "Errors",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "rate-limit",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "retry-choreo",
		label: "Retry choreography",
		description: "Two retryable 503 responses followed by success.",
		group: "Errors",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "retry-choreo",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-auth-fail",
		label: "401 unauthorized",
		description: "Reproduce the current bare authentication failure.",
		group: "Errors",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "auth",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-proxy-html",
		label: "Proxy HTML",
		description: "An SSO proxy returns HTML instead of an oRPC response.",
		group: "Errors",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "proxy-html",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-too-large",
		label: "413 too large",
		description: "A terminal payload-size rejection.",
		group: "Errors",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "too-large",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "upload-server-error",
		label: "500 server error",
		description: "A terminal internal-server failure without automatic retry.",
		group: "Errors",
		profile: "fixture",
		argv: ["upload"],
		stubBehavior: "server-error",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "retry-queue-populated",
		label: "Populated retry queue",
		description: "Mixed retryable and permanent failures with confirmation.",
		group: "States",
		profile: "fixture",
		argv: ["upload", "--retry"],
		stubBehavior: "ok",
		env: {},
		fixture: "retry-queue",
		agentState: "clean",
	},
	{
		name: "whoami-signed-in",
		label: "Signed-in identity",
		description: "A healthy API-key identity response.",
		group: "States",
		profile: "fixture",
		argv: ["whoami"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "whoami-with-failures",
		label: "Identity + retry warning",
		description: "Signed-in identity with a populated local failure queue.",
		group: "States",
		profile: "fixture",
		argv: ["whoami"],
		stubBehavior: "ok",
		env: {},
		fixture: "retry-queue",
		agentState: "clean",
	},
	{
		name: "whoami-auth-fail",
		label: "Expired identity",
		description: "Authentication verification receives a 401.",
		group: "Errors",
		profile: "fixture",
		argv: ["whoami"],
		stubBehavior: "auth",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "enable-flow",
		label: "Enable hooks",
		description:
			"Install hooks into fake config and optionally upload fixture sessions.",
		group: "States",
		profile: "fixture",
		argv: ["enable"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "disable-flow",
		label: "Disable hooks",
		description: "Remove pre-seeded Claude and Codex hooks from fake config.",
		group: "States",
		profile: "fixture",
		argv: ["disable"],
		stubBehavior: "ok",
		env: {},
		fixture: "hooks-enabled",
		agentState: "hooks-enabled",
	},
	{
		name: "dry-run",
		label: "Dry run",
		description: "Preview selected fixture projects without network writes.",
		group: "States",
		profile: "fixture",
		argv: ["upload", "--dry-run"],
		stubBehavior: "ok",
		env: {},
		fixture: "standard",
		agentState: "clean",
	},
	{
		name: "no-color",
		label: "No color",
		description: "Render the fixture picker with NO_COLOR enabled.",
		group: "States",
		profile: "fixture",
		argv: ["upload", "--dry-run"],
		stubBehavior: "ok",
		env: { NO_COLOR: "1" },
		fixture: "standard",
		agentState: "clean",
	},
];
