import type { BuiltInLanguageSignalCategory } from "./types.js";

export interface LanguageSignalRule {
	readonly category: BuiltInLanguageSignalCategory;
	readonly ruleId: string;
	readonly surfaces: readonly string[];
}

// Deterministic surface lists only: no stemming, fuzzy matching, leetspeak,
// or broad context awareness. The scanner only handles immediately adjacent
// explicit negation. Identity slurs stay excluded. "hellish", bare "absolutely
// right", and bare "exactly" are deliberate non-surfaces (boundary and ordering
// semantics depend on them).
export const LANGUAGE_SIGNAL_RULES: readonly LanguageSignalRule[] = [
	{
		category: "negative",
		ruleId: "negative.fishy",
		surfaces: ["fishy"],
	},
	{
		category: "negative",
		ruleId: "negative.did-not-work",
		surfaces: [
			"didn't work",
			"didnt work",
			"did not work",
			"doesn't work",
			"doesnt work",
			"does not work",
			"isn't working",
			"isnt working",
			"is not working",
			"not working",
			"still not working",
			"won't work",
			"wont work",
			"will not work",
			"never worked",
			"stopped working",
		],
	},
	{
		category: "negative",
		ruleId: "negative.unchanged",
		surfaces: ["exactly the same"],
	},
	{
		category: "negative",
		ruleId: "negative.not-good",
		surfaces: ["not good"],
	},
	{
		category: "negative",
		ruleId: "negative.dislike",
		surfaces: [
			"don't like",
			"dont like",
			"do not like",
			"doesn't like",
			"doesnt like",
			"does not like",
			"didn't like",
			"didnt like",
			"did not like",
		],
	},
	{
		category: "swear",
		ruleId: "swear.fuck",
		surfaces: [
			"fuck",
			"fucks",
			"fucked",
			"fucking",
			"fuckin",
			"fucker",
			"fuckers",
			"motherfucker",
			"motherfuckers",
			"motherfucking",
			"fuckup",
			"fuckups",
			"clusterfuck",
			"clusterfucks",
			"fuckery",
		],
	},
	{
		category: "swear",
		ruleId: "swear.shit",
		surfaces: [
			"shit",
			"shits",
			"shitty",
			"shittier",
			"shittiest",
			"shitting",
			"shat",
			"bullshit",
			"horseshit",
			"shitshow",
			"shitshows",
			"shitload",
			"shitloads",
			"shithole",
			"shitholes",
			"shitstorm",
			"shitstorms",
			"apeshit",
			"batshit",
		],
	},
	{
		category: "swear",
		ruleId: "swear.ass",
		surfaces: [
			"ass",
			"asses",
			"asshole",
			"assholes",
			"asshat",
			"asshats",
			"arse",
			"arses",
			"arsehole",
			"arseholes",
			"dumbass",
			"dumbasses",
			"jackass",
			"jackasses",
			"smartass",
			"smartasses",
			"badass",
			"badasses",
			"kickass",
			"half-assed",
			"half assed",
		],
	},
	{
		category: "swear",
		ruleId: "swear.bitch",
		surfaces: [
			"bitch",
			"bitches",
			"bitched",
			"bitching",
			"bitchy",
			"sonofabitch",
			"son of a bitch",
			"sons of bitches",
		],
	},
	{
		category: "swear",
		ruleId: "swear.bastard",
		surfaces: ["bastard", "bastards"],
	},
	{
		category: "swear",
		ruleId: "swear.dick",
		surfaces: ["dick", "dicks", "dickhead", "dickheads"],
	},
	{
		category: "swear",
		ruleId: "swear.cock",
		surfaces: ["cock", "cocksucker", "cocksuckers"],
	},
	{
		category: "swear",
		ruleId: "swear.cunt",
		surfaces: ["cunt", "cunts"],
	},
	{
		category: "swear",
		ruleId: "swear.prick",
		surfaces: ["prick", "pricks"],
	},
	{
		category: "swear",
		ruleId: "swear.twat",
		surfaces: ["twat", "twats"],
	},
	{
		category: "swear",
		ruleId: "swear.wanker",
		surfaces: ["wanker", "wankers", "wank", "wanking"],
	},
	{
		category: "swear",
		ruleId: "swear.bollocks",
		surfaces: ["bollocks", "bollocking"],
	},
	{
		category: "swear",
		ruleId: "swear.bugger",
		surfaces: ["bugger", "buggered", "buggering"],
	},
	{
		category: "swear",
		ruleId: "swear.bloody",
		surfaces: ["bloody"],
	},
	{
		category: "swear",
		ruleId: "swear.douche",
		surfaces: ["douche", "douchebag", "douchebags"],
	},
	{
		category: "swear",
		ruleId: "swear.piss",
		surfaces: ["piss", "pisses", "pissed", "pissing"],
	},
	{
		category: "swear",
		ruleId: "swear.damn",
		surfaces: [
			"damn",
			"damns",
			"damned",
			"damnit",
			"dammit",
			"goddamn",
			"goddamned",
			"goddammit",
			"goddamnit",
		],
	},
	{
		category: "swear",
		ruleId: "swear.hell",
		surfaces: ["hell"],
	},
	{
		category: "swear",
		ruleId: "swear.crap",
		surfaces: [
			"crap",
			"crappy",
			"crappier",
			"crappiest",
			"crapped",
			"crapload",
			"craploads",
			"bullcrap",
		],
	},
	{
		category: "swear",
		ruleId: "swear.suck",
		surfaces: ["suck", "sucks", "sucked", "sucking", "sucky"],
	},
	{
		category: "swear",
		ruleId: "swear.turd",
		surfaces: ["turd", "turds"],
	},
	{
		category: "swear",
		ruleId: "swear.screw",
		surfaces: [
			"screw it",
			"screw this",
			"screw that",
			"screwed up",
			"screw up",
			"screw ups",
			"screwup",
			"screwups",
			"screw-up",
			"screw-ups",
		],
	},
	{
		category: "swear",
		ruleId: "swear.minced",
		surfaces: [
			"darn",
			"darned",
			"dang",
			"heck",
			"freaking",
			"freakin",
			"frigging",
			"friggin",
			"fricking",
			"frickin",
			"effing",
		],
	},
	{
		category: "swear",
		ruleId: "swear.wtf",
		surfaces: ["wtf"],
	},
	{
		category: "swear",
		ruleId: "swear.abbreviations",
		surfaces: ["ffs", "fml", "stfu", "omfg", "gtfo"],
	},
	{
		category: "apology",
		ruleId: "apology.sorry",
		surfaces: [
			"sorry",
			"i'm sorry",
			"i am sorry",
			"we're sorry",
			"we are sorry",
			"so sorry",
			"really sorry",
			"very sorry",
			"terribly sorry",
			"deeply sorry",
			"truly sorry",
			"sincerely sorry",
		],
	},
	{
		category: "apology",
		ruleId: "apology.apology",
		surfaces: [
			"apology",
			"apologies",
			"my apologies",
			"our apologies",
			"sincere apologies",
			"sincerest apologies",
			"deepest apologies",
			"i owe you an apology",
		],
	},
	{
		category: "apology",
		ruleId: "apology.apologize",
		surfaces: [
			"apologize",
			"apologizes",
			"apologized",
			"apologizing",
			"apologise",
			"apologises",
			"apologised",
			"apologising",
		],
	},
	{
		category: "apology",
		ruleId: "apology.mistake",
		surfaces: [
			"my bad",
			"my mistake",
			"our mistake",
			"my fault",
			"our fault",
			"my error",
			"my oversight",
			"i was wrong",
			"we were wrong",
			"i got that wrong",
			"i got it wrong",
			"i made a mistake",
			"we made a mistake",
			"i made an error",
			"i messed up",
			"we messed up",
			"i screwed up",
			"we screwed up",
			"that's on me",
			"that is on me",
			"that's my fault",
			"that is my fault",
			"that was my fault",
			"mea culpa",
		],
	},
	{
		category: "apology",
		ruleId: "apology.correction",
		surfaces: [
			"i stand corrected",
			"i take that back",
			"i take it back",
			"i misspoke",
			"i misread",
			"i misunderstood",
			"you were right",
			"you were absolutely right",
			"you were absolutely correct",
			"you were correct",
		],
	},
	{
		category: "apology",
		ruleId: "apology.regret",
		surfaces: ["i regret", "we regret", "regrettably", "regretfully"],
	},
	{
		category: "apology",
		ruleId: "apology.pardon",
		surfaces: [
			"pardon",
			"pardon me",
			"i beg your pardon",
			"beg your pardon",
			"pardon my french",
		],
	},
	{
		category: "apology",
		ruleId: "apology.forgive",
		surfaces: ["forgive me", "please forgive"],
	},
	{
		category: "apology",
		ruleId: "apology.excuse",
		surfaces: ["excuse me", "excuse my french"],
	},
	{
		category: "apology",
		ruleId: "apology.oops",
		surfaces: ["oops", "whoops", "oopsie", "whoopsie"],
	},
	{
		category: "positive",
		ruleId: "positive.agreement",
		surfaces: [
			"agreed",
			"absolutely",
			"correct",
			"precisely",
			"indeed",
			"definitely",
			"certainly",
			"totally",
			"for sure",
			"fair enough",
			"fair point",
			"good point",
			"great point",
			"excellent point",
			"valid point",
			"well said",
			"spot on",
			"spot-on",
			"bang on",
			"on point",
			"makes sense",
			"that makes sense",
			"that's true",
			"that is true",
			"i agree",
			"we agree",
			"totally agree",
			"completely agree",
			"fully agree",
			"couldn't agree more",
			"could not agree more",
		],
	},
	{
		category: "positive",
		ruleId: "positive.praise",
		surfaces: [
			"good",
			"great",
			"nice",
			"perfect",
			"excellent",
			"awesome",
			"fantastic",
			"brilliant",
			"amazing",
			"wonderful",
			"superb",
			"outstanding",
			"stellar",
			"terrific",
			"incredible",
			"impressive",
			"beautiful",
			"elegant",
			"marvelous",
			"magnificent",
			"phenomenal",
			"flawless",
			"solid",
			"neat",
			"slick",
			"lovely",
			"gorgeous",
			"top notch",
			"top-notch",
			"first rate",
			"first-rate",
			"world class",
			"world-class",
			"chef's kiss",
		],
	},
	{
		category: "positive",
		ruleId: "positive.thanks",
		surfaces: [
			"thanks",
			"thank you",
			"thx",
			"many thanks",
			"thanks a lot",
			"thanks so much",
			"much obliged",
			"cheers",
		],
	},
	{
		category: "positive",
		ruleId: "positive.appreciation",
		surfaces: [
			"appreciate it",
			"appreciated",
			"i appreciate",
			"we appreciate",
			"much appreciated",
			"grateful",
			"gratitude",
			"kudos",
			"hats off",
			"shoutout",
			"shout out",
			"shout-out",
			"bravo",
			"well played",
		],
	},
	{
		category: "positive",
		ruleId: "positive.love",
		surfaces: ["love", "loved", "loving", "love it", "adore"],
	},
	{
		category: "positive",
		ruleId: "positive.good-job",
		surfaces: [
			"good job",
			"good work",
			"great job",
			"great work",
			"nice job",
			"nice work",
			"perfect job",
			"perfect work",
			"excellent job",
			"excellent work",
			"awesome job",
			"awesome work",
			"fantastic job",
			"fantastic work",
			"brilliant job",
			"brilliant work",
			"amazing job",
			"amazing work",
			"wonderful job",
			"wonderful work",
			"outstanding job",
			"outstanding work",
			"stellar job",
			"stellar work",
			"superb job",
			"superb work",
			"incredible job",
			"incredible work",
			"terrific job",
			"terrific work",
			"phenomenal job",
			"phenomenal work",
			"solid job",
			"solid work",
			"good stuff",
			"great stuff",
			"nice one",
			"good one",
			"keep up the good work",
			"keep it up",
		],
	},
	{
		category: "positive",
		ruleId: "positive.done",
		surfaces: [
			"well done",
			"nicely done",
			"beautifully done",
			"nailed it",
			"you nailed it",
			"crushed it",
			"killed it",
			"smashed it",
			"aced it",
			"hit the nail on the head",
			"that did the trick",
			"did the trick",
			"that did it",
		],
	},
	{
		category: "positive",
		ruleId: "positive.question",
		surfaces: [
			"good question",
			"great question",
			"excellent question",
			"good call",
			"great call",
			"nice call",
			"good catch",
			"great catch",
			"nice catch",
			"excellent catch",
			"good thinking",
			"good idea",
			"great idea",
			"excellent idea",
			"nice idea",
			"good eye",
		],
	},
	{
		category: "positive",
		ruleId: "positive.right",
		surfaces: [
			"you're right",
			"you are right",
			"that's right",
			"that is right",
			"you're correct",
			"you are correct",
			"that's correct",
			"that is correct",
			"you're absolutely right",
			"you are absolutely right",
			"that's absolutely right",
			"that is absolutely right",
			"you're absolutely correct",
			"you are absolutely correct",
			"that's absolutely correct",
			"that is absolutely correct",
		],
	},
	{
		category: "positive",
		ruleId: "positive.looks-good",
		surfaces: [
			"looks good",
			"sounds good",
			"looks great",
			"sounds great",
			"looks perfect",
			"sounds perfect",
			"looks awesome",
			"looks fantastic",
			"looks right",
			"sounds right",
			"feels right",
			"looks correct",
			"lgtm",
			"sgtm",
			"works for me",
			"fine by me",
			"works great",
			"works perfectly",
			"works flawlessly",
			"working perfectly",
			"works like a charm",
			"like a charm",
			"worked perfectly",
			"works now",
			"it worked",
			"that worked",
			"that fixed it",
			"problem solved",
		],
	},
	{
		category: "positive",
		ruleId: "positive.approval",
		surfaces: [
			"ship it",
			"let's do it",
			"lets do it",
			"go for it",
			"sounds like a plan",
		],
	},
];
