import { createHash } from "node:crypto";
import {
	GITLEAKS_CONFIG_SHA256,
	GITLEAKS_CONFIG_URL,
	GITLEAKS_VERSION,
	SELECTED_RULES,
} from "./ruleset-config.js";

const VENDOR_PATH = new URL("../vendor/gitleaks.toml", import.meta.url);

async function main(): Promise<void> {
	const response = await fetch(GITLEAKS_CONFIG_URL);
	if (!response.ok) {
		throw new Error(
			`Unable to download pinned Gitleaks config (status ${response.status})`,
		);
	}

	const source = await response.text();
	verifyChecksum(source);
	const selectedBlocks = extractSelectedRuleBlocks(source);
	const header = [
		"# Generated by scripts/vendor-gitleaks.ts. Do not edit by hand.",
		`# Source: Gitleaks ${GITLEAKS_VERSION} config/gitleaks.toml`,
		`# SHA-256: ${GITLEAKS_CONFIG_SHA256}`,
		"",
	].join("\n");
	await Bun.write(VENDOR_PATH, `${header}${selectedBlocks.join("\n")}`);
}

function verifyChecksum(source: string): void {
	const actual = createHash("sha256").update(source).digest("hex");
	if (actual !== GITLEAKS_CONFIG_SHA256) {
		throw new Error("Pinned Gitleaks config checksum did not match");
	}
}

function extractSelectedRuleBlocks(source: string): string[] {
	const ruleBlocks = source.split(/(?=^\[\[rules\]\]$)/mu);
	const blocksById = new Map<string, string>();

	for (const block of ruleBlocks) {
		const id = block.match(/^id = "([^"]+)"$/mu)?.[1];
		if (id) {
			blocksById.set(id, block.trim());
		}
	}

	return SELECTED_RULES.map(({ sourceId }) => {
		const block = blocksById.get(sourceId);
		if (!block) {
			throw new Error(`Pinned Gitleaks rule is missing: ${sourceId}`);
		}
		return `${block}\n`;
	});
}

await main();
